<?php

namespace Database\Seeders;

use App\Models\Comic;
use App\Models\Publisher;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ComicSeeder extends Seeder
{
    public function run(): void
    {
        $marvel = Publisher::where('name', 'Marvel Comics')->first();
        $dc = Publisher::where('name', 'DC Comics')->first();
        $image = Publisher::where('name', 'Image Comics')->first();
        $shueisha = Publisher::where('name', 'Shueisha')->first();
        $kodansha = Publisher::where('name', 'Kodansha')->first();
        $viz = Publisher::where('name', 'VIZ Media')->first();

        $superheroes = Category::where('slug', 'superheroes')->first();
        $manga = Category::where('slug', 'manga')->first();
        $scifi = Category::where('slug', 'sci-fi')->first();
        $action = Category::where('slug', 'accion')->first();
        $horror = Category::where('slug', 'horror')->first();
        $shonen = Category::where('slug', 'shonen')->first();
        $seinen = Category::where('slug', 'seinen')->first();
        $fantasy = Category::where('slug', 'fantasy')->first();

        $comics = [
            [
                'title' => 'Spider-Man: No Way Home',
                'description' => 'La adaptación del exitoso film. Peter Parker enfrenta las consecuencias de revelar su identidad.',
                'publisher_id' => $marvel->id,
                'price' => 25.99,
                'stock' => 15,
                'isbn' => '9781302946738',
                'pages' => 112,
                'language' => 'es',
                'publication_date' => '2023-05-15',
                'is_featured' => true,
                'is_new_release' => true,
                'categories' => [$superheroes->id, $action->id],
            ],
            [
                'title' => 'The Amazing Spider-Man Vol. 1',
                'description' => 'El inicio de una nueva era para el trepamuros. Aventuras clásicas remasterizadas.',
                'publisher_id' => $marvel->id,
                'price' => 29.99,
                'stock' => 8,
                'isbn' => '9781302915407',
                'pages' => 136,
                'language' => 'es',
                'publication_date' => '2022-03-10',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$superheroes->id, $action->id],
            ],
            [
                'title' => 'Batman: The Killing Joke',
                'description' => 'La obra maestra de Alan Moore y Brian Bolland sobre el Joker.',
                'publisher_id' => $dc->id,
                'price' => 32.50,
                'stock' => 12,
                'isbn' => '9781401216672',
                'pages' => 64,
                'language' => 'es',
                'publication_date' => '1988-03-01',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$superheroes->id, $horror->id],
            ],
            [
                'title' => 'Justice League Dark',
                'description' => 'Los héroes mágicos del universo DC se unen para combatir amenazas sobrenaturales.',
                'publisher_id' => $dc->id,
                'price' => 27.99,
                'stock' => 10,
                'isbn' => '9781401237665',
                'pages' => 144,
                'language' => 'es',
                'publication_date' => '2023-01-20',
                'is_featured' => false,
                'is_new_release' => true,
                'categories' => [$superheroes->id, $fantasy->id],
            ],
            [
                'title' => 'Spawn Vol. 1',
                'description' => 'El legendario antihéroe de Todd McFarlane regresa del infierno.',
                'publisher_id' => $image->id,
                'price' => 24.99,
                'stock' => 20,
                'isbn' => '9781607060000',
                'pages' => 176,
                'language' => 'es',
                'publication_date' => '1992-05-01',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$superheroes->id, $horror->id],
            ],
            [
                'title' => 'The Walking Dead Compendium Vol. 1',
                'description' => 'La saga zombie definitiva. Los primeros 48 números en un solo volumen.',
                'publisher_id' => $image->id,
                'price' => 59.99,
                'stock' => 5,
                'isbn' => '9781607060765',
                'pages' => 1088,
                'language' => 'es',
                'publication_date' => '2009-09-23',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$horror->id, $action->id],
            ],
            [
                'title' => 'One Piece Vol. 1',
                'description' => 'La aventura de Luffy comienza. En busca del tesoro más grande del mundo.',
                'publisher_id' => $shueisha->id,
                'price' => 18.99,
                'stock' => 30,
                'isbn' => '9784088725093',
                'pages' => 208,
                'language' => 'es',
                'publication_date' => '1997-12-24',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $shonen->id, $action->id],
            ],
            [
                'title' => 'Naruto Vol. 1',
                'description' => 'El ninja más ruidoso del mundo ninja. La historia de Naruto Uzumaki comienza.',
                'publisher_id' => $shueisha->id,
                'price' => 17.99,
                'stock' => 25,
                'isbn' => '9784088728636',
                'pages' => 192,
                'language' => 'es',
                'publication_date' => '1999-09-21',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $shonen->id, $action->id],
            ],
            [
                'title' => 'Attack on Titan Vol. 1',
                'description' => 'La humanidad está al borde de la extinción. Los titanes han llegado.',
                'publisher_id' => $kodansha->id,
                'price' => 19.99,
                'stock' => 18,
                'isbn' => '9781612620244',
                'pages' => 194,
                'language' => 'es',
                'publication_date' => '2012-06-19',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $shonen->id, $action->id, $horror->id],
            ],
            [
                'title' => 'Death Note Vol. 1',
                'description' => 'Un cuaderno que mata. Light Yagami encuentra el poder definitivo.',
                'publisher_id' => $shueisha->id,
                'price' => 16.99,
                'stock' => 22,
                'isbn' => '9781421501680',
                'pages' => 200,
                'language' => 'es',
                'publication_date' => '2005-10-10',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $shonen->id],
            ],
            [
                'title' => 'My Hero Academia Vol. 1',
                'description' => 'En un mundo donde todos tienen superpoderes, Izuku Midoriya no tiene ninguno.',
                'publisher_id' => $shueisha->id,
                'price' => 18.99,
                'stock' => 28,
                'isbn' => '9781421582696',
                'pages' => 192,
                'language' => 'es',
                'publication_date' => '2015-08-04',
                'is_featured' => true,
                'is_new_release' => true,
                'categories' => [$manga->id, $shonen->id, $superheroes->id],
            ],
            [
                'title' => 'Demon Slayer Vol. 1',
                'description' => 'Tanjiro debe convertirse en cazador de demonios para salvar a su hermana.',
                'publisher_id' => $shueisha->id,
                'price' => 19.99,
                'stock' => 35,
                'isbn' => '9781974700523',
                'pages' => 208,
                'language' => 'es',
                'publication_date' => '2018-07-03',
                'is_featured' => true,
                'is_new_release' => true,
                'categories' => [$manga->id, $shonen->id, $action->id],
            ],
            [
                'title' => 'Berserk Deluxe Edition Vol. 1',
                'description' => 'La obra maestra de Kentaro Miura. Guts, el espadachín negro, busca venganza.',
                'publisher_id' => $kodansha->id,
                'price' => 49.99,
                'stock' => 8,
                'isbn' => '9781506711980',
                'pages' => 696,
                'language' => 'es',
                'publication_date' => '2019-02-27',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $seinen->id, $fantasy->id, $horror->id],
            ],
            [
                'title' => 'Chainsaw Man Vol. 1',
                'description' => 'Denji es un chico con una motosierra en la cabeza que caza demonios.',
                'publisher_id' => $shueisha->id,
                'price' => 20.99,
                'stock' => 30,
                'isbn' => '9781974709939',
                'pages' => 192,
                'language' => 'es',
                'publication_date' => '2020-10-06',
                'is_featured' => true,
                'is_new_release' => true,
                'categories' => [$manga->id, $shonen->id, $action->id, $horror->id],
            ],
            [
                'title' => 'Jujutsu Kaisen Vol. 1',
                'description' => 'Yuji Itadori se traga un dedo maldito y se convierte en anfitrión de un demonio.',
                'publisher_id' => $shueisha->id,
                'price' => 19.99,
                'stock' => 26,
                'isbn' => '9781974710027',
                'pages' => 192,
                'language' => 'es',
                'publication_date' => '2019-12-03',
                'is_featured' => true,
                'is_new_release' => true,
                'categories' => [$manga->id, $shonen->id, $action->id],
            ],
            [
                'title' => 'Invincible Vol. 1',
                'description' => 'Mark Grayson descubre que tiene superpoderes, pero ser superhéroe es más complicado de lo que pensaba.',
                'publisher_id' => $image->id,
                'price' => 28.99,
                'stock' => 14,
                'isbn' => '9781582403939',
                'pages' => 144,
                'language' => 'es',
                'publication_date' => '2003-06-01',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$superheroes->id, $action->id],
            ],
            [
                'title' => 'Saga Vol. 1',
                'description' => 'Una epopeya espacial sobre dos soldados de mundos enemigos que se enamoran.',
                'publisher_id' => $image->id,
                'price' => 26.99,
                'stock' => 16,
                'isbn' => '9781607066019',
                'pages' => 160,
                'language' => 'es',
                'publication_date' => '2012-10-23',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$scifi->id, $fantasy->id, $action->id],
            ],
            [
                'title' => 'Tokyo Ghoul Vol. 1',
                'description' => 'Ken Kaneki se convierte en mitad humano, mitad ghoul tras un encuentro fatal.',
                'publisher_id' => $shueisha->id,
                'price' => 21.99,
                'stock' => 19,
                'isbn' => '9781421580364',
                'pages' => 224,
                'language' => 'es',
                'publication_date' => '2014-06-17',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $seinen->id, $horror->id, $action->id],
            ],
            [
                'title' => 'Fullmetal Alchemist Vol. 1',
                'description' => 'Edward y Alphonse Elric buscan la Piedra Filosofal para recuperar lo que perdieron.',
                'publisher_id' => $shueisha->id,
                'price' => 17.99,
                'stock' => 23,
                'isbn' => '9781591169208',
                'pages' => 192,
                'language' => 'es',
                'publication_date' => '2005-05-03',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $shonen->id, $fantasy->id, $action->id],
            ],
            [
                'title' => 'Watchmen',
                'description' => 'La obra maestra de Alan Moore que revolucionó los comics de superhéroes.',
                'publisher_id' => $dc->id,
                'price' => 39.99,
                'stock' => 11,
                'isbn' => '9781401245252',
                'pages' => 416,
                'language' => 'es',
                'publication_date' => '1987-06-01',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$superheroes->id, $scifi->id],
            ],
            [
                'title' => 'X-Men: Days of Future Past',
                'description' => 'Un futuro distópico donde los mutantes son cazados. Los X-Men deben evitarlo.',
                'publisher_id' => $marvel->id,
                'price' => 24.99,
                'stock' => 13,
                'isbn' => '9780785164531',
                'pages' => 128,
                'language' => 'es',
                'publication_date' => '1981-01-01',
                'is_featured' => false,
                'is_new_release' => false,
                'categories' => [$superheroes->id, $scifi->id, $action->id],
            ],
            [
                'title' => 'The Sandman Vol. 1: Preludes & Nocturnes',
                'description' => 'Neil Gaiman presenta a Morpheus, el Señor de los Sueños.',
                'publisher_id' => $dc->id,
                'price' => 31.99,
                'stock' => 9,
                'isbn' => '9781401225759',
                'pages' => 240,
                'language' => 'es',
                'publication_date' => '1991-03-01',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$fantasy->id, $horror->id],
            ],
            [
                'title' => 'Akira Vol. 1',
                'description' => 'La obra maestra cyberpunk de Katsuhiro Otomo. Neo-Tokyo, 2019.',
                'publisher_id' => $kodansha->id,
                'price' => 44.99,
                'stock' => 7,
                'isbn' => '9781935429005',
                'pages' => 364,
                'language' => 'es',
                'publication_date' => '1984-12-20',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $seinen->id, $scifi->id, $action->id],
            ],
            [
                'title' => 'Vagabond Vol. 1',
                'description' => 'La historia del legendario samurái Miyamoto Musashi por Takehiko Inoue.',
                'publisher_id' => $kodansha->id,
                'price' => 22.99,
                'stock' => 15,
                'isbn' => '9781421522470',
                'pages' => 272,
                'language' => 'es',
                'publication_date' => '1998-09-17',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $seinen->id, $action->id],
            ],
            [
                'title' => 'Hunter x Hunter Vol. 1',
                'description' => 'Gon Freecss quiere ser un Hunter, igual que su padre desaparecido.',
                'publisher_id' => $shueisha->id,
                'price' => 18.99,
                'stock' => 21,
                'isbn' => '9781421501840',
                'pages' => 208,
                'language' => 'es',
                'publication_date' => '2005-04-05',
                'is_featured' => true,
                'is_new_release' => false,
                'categories' => [$manga->id, $shonen->id, $action->id, $fantasy->id],
            ],
        ];

        foreach ($comics as $comicData) {
            $categories = $comicData['categories'];
            unset($comicData['categories']);
            
            $comic = Comic::create($comicData);
            $comic->categories()->attach($categories);
        }
    }
}
